services:
  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-volume:/data/db

volumes:
  mongo-db-volume:
    name: posture-bot-database-volume